index:
  path: /
  controller: App\Controller\TestController::helloEn
  defaults:
    twig: false

twig:
  path: /twig
  controller: App\Controller\TestController::helloEn
  defaults:
    twig: true

index-fr:
  path: /fr/
  controller: App\Controller\TestController::helloFr
  defaults:
    twig: false

twig-fr:
  path: /fr/twig
  controller: App\Controller\TestController::helloFr
  defaults:
    twig: true

user-view:
  path: /user/{id}
  controller: App\Controller\UserController::view

user-view-fr:
  path: /fr/user/{id}
  controller: App\Controller\UserController::viewFr

user-index:
  path: /users
  controller: App\Controller\UserController::index

user-index-fr:
  path: /fr/users
  controller: App\Controller\UserController::indexFr

contact:
  path: /contact
  controller: App\Controller\ClientController::new

contact-fr:
  path: /fr/contact
  controller: App\Controller\ClientController::newFr
