index:
  path: /
  controller: App\Controller\TestController::hello
  defaults:
    twig: false
twig:
  path: /twig
  controller: App\Controller\TestController::hello
  defaults:
    twig: true

user-view:
  path: /user/{id}
  controller: App\Controller\UserController::view

user-index:
  path: /users
  controller: App\Controller\UserController::index

contact:
  path: /contact
  controller: App\Controller\ClientController::new