#index:
#    path: /
#    controller: App\Controller\DefaultController::index
test:
  path: /
  controller: App\Controller\TestController::hello
twig:
  path: /twig
  controller: App\Controller\TestController::twig